- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "duplicate"
  color: "cfd8d7"
  description: "This issue or pull request already exists"

- name: "enhancement"
  description: "New feature or request"
  color: "a2eeef"

- name: "good first issue"
  description: "Good for newcomers"
  color: "7057ff"

- name: "help wanted"
  description: "Extra attention is needed"
  color: "008672"

- name: "invalid"
  description: "This doesn't seem right"
  color: "e4e669"

- name: "question"
  description: "Further information is requested"
  color: "d876e3"

- name: "wontfix"
  description: "This will not be worked on"
  color: "ffffff"

- name: "bug:minecraft"
  description: ""
  color: "bc180e"

- name: "bug:paper"
  description: "bug in PaperMC"
  color: "e51b33"

- name: "bug:plugin"
  description: "bug in Plugin"
  color: "e99695"

- name: "In Game"
  description: ""
  color: "14d95d"

- name: "In Game Incident"
  description: ""
  color: "ee9699"

- name: "new comer"
  description: ""
  color: "0052cc"

- name: "Server Incident"
  description: ""
  color: "d93f0b"

- name: "Server Maintenance"
  description: ""
  color: "4c38fa"
