version: "3.7"

services:
  paper:
    image: ghcr.io/sksat/papermc-docker:1.17.1@sha256:da46cf8a7fc514151784dcb782f7971487f0b094680d4699c30ab9ac2253dd6d
    restart: always

    stdin_open: true
    ports:
      - 9225:9225
      - 25565:25565
      - 25575:25575
    environment:
      JAVA_TOOL_OPTIONS: "-Xms1G -Xmx1G"
    volumes:
      - ./data:/app
