version: "3.7"

services:
  paper:
    image: ghcr.io/sksat/papermc-docker:1.17.1@sha256:1ce38954bf14540a8d7ea79b1863c5bb2e4c795be51ef16137263e4b7b016741
    restart: always

    stdin_open: true
    ports:
      - 9225:9225
      - 25565:25565
      - 25575:25575
    environment:
      JAVA_TOOL_OPTIONS: "-Xms1G -Xmx1G"
    volumes:
      - ./data:/app
