version: "3.7"

services:
  paper:
    image: ghcr.io/sksat/papermc-docker:1.17.1@sha256:a26fafe31e2fd523839428ae7c067d7c024f274e592fa12a36aa828073790d62
    restart: always

    stdin_open: true
    ports:
      - 9225:9225
      - 25565:25565
      - 25575:25575
    environment:
      JAVA_TOOL_OPTIONS: "-Xms2G -Xmx2G"
    volumes:
      - ./data:/app
