version: "3.7"

services:
  paper:
    image: ghcr.io/sksat/papermc-docker:1.17.1@sha256:95b3ce3f6bc527fe357e2fe5436caf49cf9253ec5382acbbeec728672dd4e8e8
    restart: always

    stdin_open: true
    ports:
      - 9225:9225
      - 25565:25565
      - 25575:25575
    environment:
      JAVA_TOOL_OPTIONS: "-Xms2G -Xmx2G"
    volumes:
      - ./data:/app
